### ISSUE TITLE
URDF Visualization in VR

### ISSUE THREAD

**Issue by hu-po** [vuer-ai/vuer#13] opened 2024-05-01 18:55 UTC
Thanks for the great repo! I am running into issues when trying to visualize a URDF file in a VR headset. I can run the mars rover example fine and see it in the headset with textures/materials. My URDF file also works fine on the browser (though it has the white default material even though material is defined in the urdf). When I try my URDF file on the VR headset (QuestPro via ngrok) I cannot see anything (meshes or textures). I have tried various formats (obj, gltf, glb) and different materials, but still no luck. Any ideas around what might be happening? Or how I could set a default material of some sort for the URDF?

**Comment by RogerQi** [comment] 2024-05-02 01:17
Hello Hugo,

Thanks for your interest! For URDF files that I have in my hands - they work in both the VR headset and the browser. I don't know if it is possible, but if you could share the URDF file that reproduces this issue, it would help locate the issue.

**Comment by hu-po** [comment] 2024-05-02 11:46
Thanks so much for the help. [Here is the URDF file I am using](https://github.com/hu-po/webstompy/tree/main/urdf/stompy), it uses `.obj` files. It has materials defined in the `.urdf` file, but I have tried removing them and also [converting the files](https://github.com/kscalelabs/teleop/blob/ff25317821fe84eeb99b3e99f820186a931256eb/opt_urdf/run.py#L54) to `.glb`, `.gltf`, and `.stl` with no luck.

I saw you are using the three.js urdf loader that I also used in a previous project. In that previous project I had to [manually set the material color for the object3d](https://github.com/hu-po/aframe-urdf/blob/a87f9048cd45935dc7689076136961b6d1948771/src/index.js#L105), I saw you are [doing something similar in vuer-ts](https://github.com/vuer-ai/vuer-ts/blob/cca518bc9f64e9c2d11b51f31900c9e499e7bc30/vuer/three_components/data_loaders.tsx#L205) but I don't know enough about three.js to have a good intuition around what could be going wrong.

Anyways, hope that gives you more context. Thanks again for the help and for providing this awesome library to the community.

**Comment by geyang** [comment] 2024-08-19 00:10
I will take a look and get back to you asap. Apologies for the delay.

**Comment by geyang** [comment] 2024-09-02 16:32
Hey @hu-po Good news for you! The production version of vuer now supports URDF drag-and-drop, as well as via the python API. See below:

https://github.com/user-attachments/assets/4f255e83-ad66-4286-9303-58d7fd2ec0fe

![canvas - 2024-09-02T122615 141](https://github.com/user-attachments/assets/259b34f4-237b-42f7-973f-46cd5ec3a5e8)

**Comment by geyang** [comment] 2024-09-02 16:48
<img width="1398" alt="Screenshot 2024-09-02 at 12 48 21 PM" src="https://github.com/user-attachments/assets/d05c2eef-4dfe-4b2b-a263-c3bf42d3963a">

there are some path issues. Closing this issue since it has been addressed now.

**Closed by geyang** 2024-09-02 16:48 UTC
