### ISSUE TITLE
Clarification regarding hand tracking data returned by HAND_MOVE event

### ISSUE THREAD

**Issue by gauravpradeep** [vuer-ai/vuer#30] opened 2024-10-18 06:51 UTC
@geyang 
I am getting hand tracking data from a meta quest 3 and wasn't able to find information regarding the following in the documentation:
1. What values of from the 25x16 values of each hand correspond to the respective wrists? I am currently working off the assumption that the first 16 values correspond to the wrists.
2. The hand tracking data is relative to the wrist transformation, does that mean the wrist is always at origin of the world frame because the position values in my "assumed" wrist matrix are always 0,0,0? Shouldn't the headset be at the origin?

**Comment by geyang** [comment] 2024-10-19 20:18
Thanks for the question. I have updated the documentation here: 

- [**Hand Tracking Example**](https://docs.vuer.ai/en/v0.0.35-rc18/examples/19_hand_tracking.html)

**Important: Please refer to the newest documentation here: [latest | Hand_tracking](https://docs.vuer.ai/en/latest/examples/19_hand_tracking.html)**

I reproduce the content below: (Last Update: 2024-10-19)

## Hand API

You can get the full pose of the hands by listening to the `HAND_MOVE` event.
You can add flags `left` and `right` to specify which hand you want to track.
The returned data looks like the following:

```typescript
/**
 * Left and right pose are relative to the wrist transformations.
 */
export type HandsData = {
  left?: Float32Array;       // 25 * 16 values.
  right?: Float32Array;      // 25 * 16 values.
  leftState: HandState;
  rightState: HandState;
};

export type HandState = {
  pinch: boolean;
  squeeze: boolean;
  tap: boolean;

  pinchValue: number;
  squeezeValue: number;
  tapValue: number;
}
```

```python
    from vuer import Vuer, VuerSession
    from vuer.schemas import Hands
    from asyncio import sleep

    app = Vuer()


    @app.add_handler("HAND_MOVE")
    async def handler(event, session):
        print(f"Movement Event: key-{event.key}", event.value)


    @app.spawn(start=True)
    async def main(session: VuerSession):
        # Important: You need to set the `stream` option to `True` to start
        # streaming the hand movement.
        session.upsert @ Hands(fps=30, stream=True, key="hands")

        while True:
            await sleep(1)
```

### Matrix format

All 4x4 transform matrices used in WebGL are stored in 16-element `Float32Arrays`.
The values are stored in the array in column-major order; that is, each column is
written into the array top-down before moving to the next column to the right and
writing it into the array. Therefore, for the array [a0, a1, a2, …, a13, a14, a15], 
the matrix looks like this:

```
                                  ⌈  a0 a4 a8 a12  ⌉
                                  |  a1 a5 a9 a13  |
                                  |  a2 a6 a10 a14 |
                                  ⌊  a3 a7 a11 a15 ⌋
```

For details, refer to the MDN documentation on [XR Rigid Body Transformation](https://developer.mozilla.org/en-US/docs/Web/API/XRRigidTransform/matrix)

### Hand Landmarks

We follow the [XR Hand](https://developer.mozilla.org/en-US/docs/Web/API/XRHand) 
conventions, and return the landmarks in a single array of `25 * 16` values in 
the following order:

| Hand joint                        | Index |  Hand joint (continue)           | Index |
|---------------------------------  |-------| ---------------------------------|-------|
| wrist                             | 0     | middle-finger-phalanx-distal    | 13    | 
| thumb-metacarpal                  | 1     | middle-finger-tip               | 14    | 
| thumb-phalanx-proximal            | 2     | ring-finger-metacarpal          | 15    | 
| thumb-phalanx-distal              | 3     | ring-finger-phalanx-proximal    | 16    | 
| thumb-tip                         | 4     | ring-finger-phalanx-intermediate | 17   | 
| index-finger-metacarpal           | 5     | ring-finger-phalanx-distal      | 18    | 
| index-finger-phalanx-proximal     | 6     | ring-finger-tip                 | 19    | 
| index-finger-phalanx-intermediate | 7     | pinky-finger-metacarpal         | 20    | 
| index-finger-phalanx-distal       | 8     | pinky-finger-phalanx-proximal   | 21    | 
| index-finger-tip                  | 9     | pinky-finger-phalanx-intermediate | 22  | 
| middle-finger-metacarpal          | 10    | pinky-finger-phalanx-distal     | 23    | 
| middle-finger-phalanx-proximal    | 11    | pinky-finger-tip                | 24    | 
| middle-finger-phalanx-intermediate | 12   | -                               | -     |

**Closed** 2024-10-19 20:21 UTC
